---
# travis-ci build steps/configuration
language: node_js

services:
  - docker

addons:
  hosts:
    - localhost

before_install:
  # install java for jmeter tests:
  # - java
  - docker ps -a
  - ip route
  - (ip route|awk '/default/ {print $3;exit;}')
  - yamllint .travis.yaml

install:
  - docker build -t dummy-app .
    - docker run -d -p 3000:3000 --name dummy-app dummy-app
  # - docker run -d -p 127.0.0.1:3000:3000 --name dummy-app dummy-app
  # - docker run -p 3000:3000 -ti dummy-app &
  # - docker-compose up --build --detach

before_script:
  # prepare test:
  - docker ps
  - curl http://localhost:3000/data/from/db
  - curl http://$HOST_IP:3000/data/from/db
  - |
    curl -X POST -H "Content-type: application/json"
    http://$HOST_IP:3000/data/into/db
    -d '[ { "aa":11 }, { "bb":22 }, { "cc":33 } ]'
  - curl http://$HOST_IP:3000/data/from/db


script:
  - docker ps -a | grep -q dummy-app
  # - python tests.py (mvn verify -f jmeter-pom.xml -Dhost=localhost

after_install:
  - docker stop dummy-app
  #- docker-compose down
