---
# travis-ci build steps/configuration
language: node_js

services:
  - docker

before_install:
  # ramp-up
  # - docker build -t dummy-app .
  # - docker run -p 3000:3000 -ti dummy-app &
  - docker-compose up --build --detach
  - docker ps -a
  # anderer quatsch
  - ip route
  - (ip route|awk '/default/ {print $3;exit;}')
  - export HOST_IP="$(ip route|awk '/default/ {print $3;exit;}')"
  - |
    docker exec dockerized_nodejs_mongodb_app_web_1
    /bin/sh -c "ip -4 route list match 0/0 | awk '{print $3" host.docker.internal"}' >> /etc/hosts"
  - curl http://$HOST_IP:3000/data/from/db
  - |
    curl -X POST -H "Content-type: application/json"
    http://$HOST_IP:3000/data/into/db
    -d '[ { "aa":11 }, { "bb":22 }, { "cc":33 } ]'
  - curl http://$HOST_IP:3000/data/from/db
  - yamllint .travis.yaml
  # ramp-down
  - docker-compose down
